import { PokemonType, StatusCondition } from '../types';

// Defines type effectiveness multipliers. Key is attacking type, nested key is defending type.
export const TYPE_EFFECTIVENESS: Record<
  PokemonType,
  Partial<Record<PokemonType, number>>
> = {
  [PokemonType.FIRE]: {
    [PokemonType.GRASS]: 2,
    [PokemonType.ICE]: 2,
    [PokemonType.BUG]: 2,
    [PokemonType.STEEL]: 2,
    [PokemonType.WATER]: 0.5,
    [PokemonType.ROCK]: 0.5,
    [PokemonType.FIRE]: 0.5,
    [PokemonType.DRAGON]: 0.5,
  },
  [PokemonType.WATER]: {
    [PokemonType.FIRE]: 2,
    [PokemonType.GROUND]: 2,
    [PokemonType.ROCK]: 2,
    [PokemonType.GRASS]: 0.5,
    [PokemonType.WATER]: 0.5,
    [PokemonType.DRAGON]: 0.5,
  },
  [PokemonType.GRASS]: {
    [PokemonType.WATER]: 2,
    [PokemonType.GROUND]: 2,
    [PokemonType.ROCK]: 2,
    [PokemonType.FIRE]: 0.5,
    [PokemonType.POISON]: 0.5,
    [PokemonType.FLYING]: 0.5,
    [PokemonType.BUG]: 0.5,
    [PokemonType.GRASS]: 0.5,
    [PokemonType.DRAGON]: 0.5,
    [PokemonType.STEEL]: 0.5,
  },
  [PokemonType.ELECTRIC]: {
    [PokemonType.WATER]: 2,
    [PokemonType.FLYING]: 2,
    [PokemonType.GRASS]: 0.5,
    [PokemonType.ELECTRIC]: 0.5,
    [PokemonType.DRAGON]: 0.5,
    [PokemonType.GROUND]: 0,
  },
  [PokemonType.NORMAL]: {
    [PokemonType.ROCK]: 0.5,
    [PokemonType.STEEL]: 0.5,
    [PokemonType.GHOST]: 0,
  },
  [PokemonType.FIGHTING]: {
    [PokemonType.NORMAL]: 2,
    [PokemonType.ICE]: 2,
    [PokemonType.ROCK]: 2,
    [PokemonType.DARK]: 2,
    [PokemonType.STEEL]: 2,
    [PokemonType.POISON]: 0.5,
    [PokemonType.FLYING]: 0.5,
    [PokemonType.PSYCHIC]: 0.5,
    [PokemonType.BUG]: 0.5,
    [PokemonType.FAIRY]: 0.5,
    [PokemonType.GHOST]: 0,
  },
  [PokemonType.FLYING]: {
    [PokemonType.GRASS]: 2,
    [PokemonType.FIGHTING]: 2,
    [PokemonType.BUG]: 2,
    [PokemonType.ROCK]: 0.5,
    [PokemonType.STEEL]: 0.5,
    [PokemonType.ELECTRIC]: 0.5,
  },
  [PokemonType.PSYCHIC]: {
    [PokemonType.FIGHTING]: 2,
    [PokemonType.POISON]: 2,
    [PokemonType.STEEL]: 0.5,
    [PokemonType.PSYCHIC]: 0.5,
    [PokemonType.DARK]: 0,
  },
  [PokemonType.ROCK]: {
    [PokemonType.FIRE]: 2,
    [PokemonType.ICE]: 2,
    [PokemonType.FLYING]: 2,
    [PokemonType.BUG]: 2,
    [PokemonType.FIGHTING]: 0.5,
    [PokemonType.GROUND]: 0.5,
    [PokemonType.STEEL]: 0.5,
  },
  [PokemonType.GROUND]: {
    [PokemonType.FIRE]: 2,
    [PokemonType.ELECTRIC]: 2,
    [PokemonType.POISON]: 2,
    [PokemonType.ROCK]: 2,
    [PokemonType.STEEL]: 2,
    [PokemonType.GRASS]: 0.5,
    [PokemonType.BUG]: 0.5,
    [PokemonType.FLYING]: 0,
  },
  [PokemonType.ICE]: {
    [PokemonType.GRASS]: 2,
    [PokemonType.GROUND]: 2,
    [PokemonType.FLYING]: 2,
    [PokemonType.DRAGON]: 2,
    [PokemonType.FIRE]: 0.5,
    [PokemonType.WATER]: 0.5,
    [PokemonType.ICE]: 0.5,
    [PokemonType.STEEL]: 0.5,
  },
  [PokemonType.BUG]: {
    [PokemonType.GRASS]: 2,
    [PokemonType.PSYCHIC]: 2,
    [PokemonType.DARK]: 2,
    [PokemonType.FIRE]: 0.5,
    [PokemonType.FIGHTING]: 0.5,
    [PokemonType.POISON]: 0.5,
    [PokemonType.FLYING]: 0.5,
    [PokemonType.GHOST]: 0.5,
    [PokemonType.STEEL]: 0.5,
    [PokemonType.FAIRY]: 0.5,
  },
  [PokemonType.POISON]: {
    [PokemonType.GRASS]: 2,
    [PokemonType.FAIRY]: 2,
    [PokemonType.POISON]: 0.5,
    [PokemonType.GROUND]: 0.5,
    [PokemonType.ROCK]: 0.5,
    [PokemonType.GHOST]: 0.5,
    [PokemonType.STEEL]: 0,
  },
  [PokemonType.GHOST]: {
    [PokemonType.PSYCHIC]: 2,
    [PokemonType.GHOST]: 2,
    [PokemonType.DARK]: 0.5,
    [PokemonType.NORMAL]: 0,
  },
  [PokemonType.STEEL]: {
    [PokemonType.ICE]: 2,
    [PokemonType.ROCK]: 2,
    [PokemonType.FAIRY]: 2,
    [PokemonType.FIRE]: 0.5,
    [PokemonType.WATER]: 0.5,
    [PokemonType.ELECTRIC]: 0.5,
    [PokemonType.STEEL]: 0.5,
  },
  [PokemonType.DRAGON]: {
    [PokemonType.DRAGON]: 2,
    [PokemonType.STEEL]: 0.5,
    [PokemonType.FAIRY]: 0,
  },
  [PokemonType.DARK]: {
    [PokemonType.PSYCHIC]: 2,
    [PokemonType.GHOST]: 2,
    [PokemonType.FIGHTING]: 0.5,
    [PokemonType.DARK]: 0.5,
    [PokemonType.FAIRY]: 0.5,
  },
  [PokemonType.FAIRY]: {
    [PokemonType.FIGHTING]: 2,
    [PokemonType.DRAGON]: 2,
    [PokemonType.DARK]: 2,
    [PokemonType.FIRE]: 0.5,
    [PokemonType.POISON]: 0.5,
    [PokemonType.STEEL]: 0.5,
  },
};

// Stat stage modifiers used in battle calculations.
export const STAT_STAGE_MULTIPLIERS: Record<number, number> = {
  [-6]: 2 / 8,
  [-5]: 2 / 7,
  [-4]: 2 / 6,
  [-3]: 2 / 5,
  [-2]: 2 / 4,
  [-1]: 2 / 3,
  [0]: 1,
  [1]: 3 / 2,
  [2]: 4 / 2,
  [3]: 5 / 2,
  [4]: 6 / 2,
  [5]: 7 / 2,
  [6]: 8 / 2,
};

// Information about status conditions, including display names, colors, and icons.
export const STATUS_CONDITION_INFO: Record<
  StatusCondition,
  { shortName: string; longName?: string; colorClass?: string; icon?: string }
> = {
  [StatusCondition.NONE]: { shortName: '' },
  [StatusCondition.PARALYZED]: {
    shortName: '麻痹',
    longName: '麻痹',
    colorClass: 'text-yellow-400 dark:text-yellow-300',
    icon: '⚡',
  },
  [StatusCondition.POISONED]: {
    shortName: '中毒',
    longName: '中毒',
    colorClass: 'text-purple-400 dark:text-purple-300',
    icon: '☠️',
  },
  [StatusCondition.BADLY_POISONED]: {
    shortName: '剧毒',
    longName: '剧毒',
    colorClass: 'text-purple-600 dark:text-purple-500',
    icon: '☣️',
  },
  [StatusCondition.BURNED]: {
    shortName: '灼伤',
    longName: '灼伤',
    colorClass: 'text-red-400 dark:text-red-300',
    icon: '🔥',
  },
  [StatusCondition.FROZEN]: {
    shortName: '冰冻',
    longName: '冰冻',
    colorClass: 'text-blue-300 dark:text-blue-200',
    icon: '❄️',
  },
  [StatusCondition.ASLEEP]: {
    shortName: '睡眠',
    longName: '睡眠',
    colorClass: 'text-gray-400 dark:text-gray-300',
    icon: '💤',
  },
  [StatusCondition.CONFUSED]: {
    shortName: '混乱',
    longName: '混乱',
    colorClass: 'text-pink-400 dark:text-pink-300',
    icon: '❓',
  },
  [StatusCondition.FLINCHED]: {
    shortName: '畏缩',
    longName: '畏缩',
    colorClass: 'text-orange-400 dark:text-orange-300',
    icon: '!',
  },
};