name: Build EdgeOne
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'
  push:
    branches: [ main ]
    paths:
      - 'server/**'

# set env variable for building
env:
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  GOOGLE_GEMINI_BASE_URL: ${{ secrets.GOOGLE_GEMINI_BASE_URL }}
  GEMINI_MODEL: ${{ secrets.GEMINI_MODEL }}

jobs:
  build-edgeone:
    runs-on: ubuntu-latest
    environment: edgeone
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'server/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./server
      run: npm ci

    - name: Install EdgeOne CLI
      run: npm install -g edgeone
    
    - name: Build project (ensure code compiles)
      working-directory: ./server
      run: npm run build

    - name: Deploy to EdgeOne
      working-directory: ./server
      run: edgeone pages deploy ./dist -n anime-pok-mon -t ${{ secrets.EDGEONE_TOKEN }}